export const SAVE_TRANSACTION = "SAVE_TRANSACTION";
export const REMOVE_TRANSACTION = "REMOVE_TRANSACTION";
export const RESET_UNREAD_SAVED = "RESET_UNREAD_SAVED";
export const CLEAR_TRANSACTIONS = "CLEAR_TRANSACTIONS";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";
export const TOGGLE_CHART = "TOGGLE_CHART";
export const SAVE_INPUT = "SAVE_INPUT";
